// <auto-generated />
namespace Alquiler.Persistence.Shared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _005DataAnnotationsForCustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_005DataAnnotationsForCustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "201805090321347_005-DataAnnotationsForCustomers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
